<%@ Page Title="Education Studies" Language="C#" MasterPageFile="~/MasterPages/Frontend.master" AutoEventWireup="true" CodeFile="EducationStudies.aspx.cs" Inherits="EducationStudies" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            width: 660px;
            height: 385px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cpMainContent" Runat="Server">
    <h1>BA (Hons) Education Studies (Top-Up)</h1>
    <div class="hardcontent">
        <div class="hardimage">
            <img src="Images/Edu.jpg" class="auto-style1" /></div>
    <h2>&nbsp;</h2>
        <h2>Course Overview</h2>
        <p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            This course is validated by the<span>&nbsp;</span><a href="https://www.derby.ac.uk/" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline; transition-property: background-color, color; transition-duration: 200ms; color: rgb(130, 181, 60); outline: none; text-decoration: none;">University of Derby</a>.</p>
        <p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            This course is designed to give you a thorough understanding of the education sector and the role it plays in society. If you want to go in to teaching or become a lecturer then this is the course to gain a strong understanding of teaching and learning methods.</p>
        <p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            Modules include:</p>
        <ul style="margin: 0px 0px 1.57143em; padding: 0px 0px 0px 20px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; list-style: square; clear: left; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Understanding anad managing behaviour</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Learning and motivation</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Learning and motivation</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Mentoring and coaching</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Education and wellbeing</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Educational independent study (double module)</li>
        </ul>
        <p>&nbsp;</p>
        
        <h2>Methods of Assesment</h2>
        <p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            Methods of assessment include:</p>
        <ul style="margin: 0px 0px 1.57143em; padding: 0px 0px 0px 20px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; list-style: square; clear: left; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Written assignments</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Presentations</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Case studies</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Research projects</li>
        </ul>
        <p>&nbsp;</p>
        
        <h2>Entry Qualifications</h2>
        <p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            Entry requirements:</p>
        <span style="color: rgb(87, 87, 87); font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Foundation degree (with an overall merit at Level 5)</span><li style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            Regular work placement of at least two days a week</li>
        <li style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Two referees (one professional and one academic)</li>
        <li style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Mature students with relevant work experience will also be considered</li>
            <p>&nbsp;</p>
        <h2>Ofsted Feedback</h2>
        <p>&quot;<span style="color: rgb(87, 87, 87); font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Enthusiastic teachers use their skills and expertise to plan exciting and challenging activities that stimulate learning and meet individual needs.&quot; (Ofsted 2013)</span></p>
            <p>&nbsp;</p>
      
        </div>
</asp:Content>