<%@ Page Title="Health and Social" Language="C#" MasterPageFile="~/MasterPages/Frontend.master" AutoEventWireup="true" CodeFile="HealthSocial.aspx.cs" Inherits="HealthSocial" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            width: 660px;
            height: 375px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cpMainContent" Runat="Server">
    <h1>FdA Children's and Young People's Services - routes in Teaching Assistants, Early Years and Health and Social Care - Full-time</h1>
    <div class="hardcontent">
        <div class="hardimage">
            <img src="Images/Health.jpg" class="auto-style1" /></div>
    <h2>&nbsp;</h2>
        <h2>Course Overview</h2>
        <p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            This course aims to develop you as a confident, knowledgeable and effective practitioner to work with children, young people and their families. The course encourages you to reflect on your practice and enhance this through the theory you learn. Your work setting is used for work-based projects, activities and research so everything you study will be relevant to your everyday work.</p>
        <span style="color: rgb(87, 87, 87); font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Modules on this course include:</span><p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        </p>
        <ul style="margin: 0px 0px 1.57143em; padding: 0px 0px 0px 20px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; list-style: square; clear: left; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Starting to Study</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Work Based Reflective Practice</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Equality and diversity</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Understanding behaviour</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Children and young people communicating</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Research methods and practice</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Children&#39;s, young people&#39;s and family rights</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Secondary research</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Working with parents and carers</li>
        </ul>
        <p>&nbsp;</p>
        
        <h2>Methods of Assesment</h2>
        <p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            Methods of assessment include:</p>
        <ul style="margin: 0px 0px 1.57143em; padding: 0px 0px 0px 20px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; list-style: square; clear: left; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Case studies</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Presentations</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Written assignments</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Time constrained exercise</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Practical</li>
        </ul>
        <p style="margin: 0px 0px 1.57143em; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            &nbsp;</p>
        
        <h2>Entry Qualifications</h2>
        <ul style="margin: 0px 0px 1.57143em; padding: 0px 0px 0px 20px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, Arial, sans-serif; font-size: 14px; vertical-align: baseline; list-style: square; clear: left; color: rgb(87, 87, 87); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">Level 3 qualification in a relevant subject</li>
            <li style="margin: 0px 0px 0.39286em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">GCSE English and maths at grade C or above (or level 2 equivalent)</li>
        </ul>
            <p>&nbsp;</p>
        <h2>Ofsted Feedback</h2>
        <p>&quot;<span style="color: rgb(87, 87, 87); font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Enthusiastic teachers use their skills and expertise to plan exciting and challenging activities that stimulate learning and meet individual needs.&quot; (Ofsted 2013)</span></p>
        <p>&nbsp;</p>
      
        </div>
</asp:Content>